apiVersion: apps/v1
kind: Deployment
metadata:
  name: postech-api
  namespace: postech-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postech-api
  template:
    metadata:
      labels:
        app: postech-api
    spec:
      containers:
      - name: postech-api
        image: 807023255505.dkr.ecr.us-east-1.amazonaws.com/postech-api:1.0.0
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: postech-api-config
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: postech-api-secret
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: postech-api-secret
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postech-api-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postech-api-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postech-api-secret
              key: DB_PASSWORD
