apiVersion: v1
kind: Secret
metadata:
  name: postech-api-secret
  namespace: postech-api
type: Opaque
data:
  DB_HOST: cG9zdGdyZXM=
  DB_PORT: NTQzMg==
  DB_NAME: Z29wb3M=
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=